apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.io.codelair.examples.kubernetesoperator
spec:
  conversion:
    strategy: None
  group: io.codelair.examples.kubernetesoperator
  names:
    kind: Sample
    listKind: SampleList
    plural: samples
    singular: sample
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                  nullable: true
            status:
              type: object
              properties:
                observedGeneration:
                  type: number
                  nullable: true
      subresources:
        status: { }
